//
//  SmileyCatalog.swift
//  MyShikiPlayer
//
//  Auto-generated by scripts/fetch_smileys.py — do not edit by hand.
//  Maps Shikimori smiley tokens (e.g. ":ololo:", ":-D", "+_+") to bundled
//  GIF filenames. Files live in Resources/Smileys/ as a folder reference.
//

import AppKit
import Foundation

enum SmileyCatalog {
    /// Token → filename (under "Smileys" subdirectory in the app bundle).
    static let entries: [String: String] = [
        ":Happy Birthday:": "99db9c56c8.gif",
        ":disappointment:": "8082ce9fa9.gif",
        ":caterpillar:": "fb25e51b33.gif",
        ":dont listen:": "459c60842c.gif",
        ":depressed2:": "983af8fc0d.gif",
        ":interested:": "bcc152e071.gif",
        ":depressed:": "190dc60827.gif",
        ":dont want:": "6925bea21b.gif",
        ":happy_cry:": "8113d8545a.gif",
        ":tea shock:": "e0a45e929d.gif",
        ":very sad2:": "59221f1074.gif",
        ":hopeless:": "a4c7d9b65e.gif",
        ":perveted:": "913d92f5f5.gif",
        ":shocked2:": "21544991db.gif",
        ":shocked3:": "cb74b8dca6.gif",
        ":shocked4:": "7bee51415c.gif",
        ":strange1:": "12077ba71b.gif",
        ":strange2:": "903954ff0b.gif",
        ":strange3:": "413df300dc.gif",
        ":strange4:": "1dc20c0590.gif",
        ":very sad:": "d7a99398af.gif",
        ":watching:": "d1966bde1b.gif",
        ":Im dead:": "40522dd3c6.gif",
        ":Warning:": "6d4ef109d5.gif",
        ":bullied:": "a60e37622d.gif",
        ":frozen2:": "f6447cf683.gif",
        ":frozen3:": "87be865cde.gif",
        ":revenge:": "f143acff91.gif",
        ":sarcasm:": "cf2e82aaef.gif",
        ":shocked:": "670768931d.gif",
        ":smoker2:": "e4d198d868.gif",
        ":strange:": "16922d16a2.gif",
        ":thumbup:": "11c02addaa.gif",
        ":twisted:": "ef8119869c.gif",
        ":advise:": "a735ed8291.gif",
        ":angry2:": "3f2c4907e2.gif",
        ":angry3:": "7cb5c96930.gif",
        ":angry4:": "3c140e35d2.gif",
        ":angry5:": "135df1404f.gif",
        ":angry6:": "0d3e603bc6.gif",
        ":animal:": "0de196c71b.gif",
        ":diplom:": "b10af7a33f.gif",
        ":frozen:": "090f1535c2.gif",
        ":happy3:": "444ab64899.gif",
        ":hurray:": "8e9792182b.gif",
        ":scared:": "ebaaa9fee1.gif",
        ":scream:": "89b16482e5.gif",
        ":shock2:": "a94e3b39b9.gif",
        ":sleepy:": "e51919a0c2.gif",
        ":smoker:": "2bc7224150.gif",
        ":stress:": "b8fdab4097.gif",
        ":study2:": "9c825531fe.gif",
        ":study3:": "5573126384.gif",
        ":Bath2:": "a1837769ab.gif",
        ":angry:": "03f83d76ab.gif",
        ":bored:": "b00bfe8a97.gif",
        ":bunch:": "7a6324f806.gif",
        ":cold2:": "ed579efd1d.gif",
        ":cool2:": "d3ce1f1b94.gif",
        ":dance:": "7314e62611.gif",
        ":dunno:": "dee28a4442.gif",
        ":evil2:": "3e89a446f4.gif",
        ":evil3:": "2a4159bcb1.gif",
        ":flute:": "34daa1901d.gif",
        ":gamer:": "126f1b1382.gif",
        ":happy:": "558cbf63b0.gif",
        ":hope2:": "db6c4dad8f.gif",
        ":hope3:": "a55acd6f65.gif",
        ":hypno:": "c049e1c48c.gif",
        ":love2:": "70f617636c.gif",
        ":noooo:": "29d3982805.gif",
        ":ololo:": "9689db36e1.gif",
        ":relax:": "d563aa54e7.gif",
        ":shock:": "fba9fd9ced.gif",
        ":sleep:": "5e1c19d364.gif",
        ":study:": "b977701d28.gif",
        ":water:": "d898e64571.gif",
        ":yahoo:": "66158247b8.gif",
        ":Cry2:": "b3203e07f8.gif",
        ":Cry3:": "7a9385670b.gif",
        ":Cry4:": "655211eccf.gif",
        ":ball:": "fb2f106aca.gif",
        ":bath:": "60ece7cb9b.gif",
        ":bdl2:": "af92d84547.gif",
        ":cold:": "67ef5869e7.gif",
        ":cool:": "3e54ce1aac.gif",
        ":cry5:": "5f03783ed4.gif",
        ":cry6:": "79985e1215.gif",
        ":evil:": "00d760b254.gif",
        ":gaze:": "50ba24d651.gif",
        ":hope:": "844ffc91e6.gif",
        ":hot2:": "8fc6cb4daf.gif",
        ":hot3:": "81bd635c72.gif",
        ":hunf:": "c3b66598bc.gif",
        ":kiss:": "5fa2539d5d.gif",
        ":liar:": "f45de63f2b.gif",
        ":love:": "c797a1967c.gif",
        ":ooph:": "b35c46b8eb.gif",
        ":play:": "8ad463c84f.gif",
        ":prcl:": "d0bb866ef6.gif",
        ":roll:": "2258236931.gif",
        ":sad2:": "ba2846d51b.gif",
        ":shy2:": "e3412a2538.gif",
        ":sick:": "caece8e6dc.gif",
        ":star:": "8fdbb32cd8.gif",
        ":tea2:": "1706b5a1a2.gif",
        ":whip:": "301ef93e98.gif",
        ":wink:": "86d08ff420.gif",
        ":Ban:": "fb58c2a9e8.gif",
        ":bdl:": "a34076934d.gif",
        ":bow:": "65f6f3ed9d.gif",
        ":bye:": "513c4b9f91.gif",
        ":cry:": "1258f67d68.gif",
        ":hot:": "7813d890a0.gif",
        ":ill:": "79d97aa78b.gif",
        ":kia:": "82a3d9535f.gif",
        ":kya:": "40772a8747.gif",
        ":lol:": "439dea9d7b.gif",
        ":oh2:": "f357f15938.gif",
        ":shy:": "32ca8fc129.gif",
        ":8):": "81e4992be5.gif",
        ":V2:": "ce23b7e345.gif",
        ":V3:": "57c51cbae7.gif",
        ":hi:": "2c43c53f6e.gif",
        ":oh:": "5e611cfc51.gif",
        ":s1:": "511a5a6c95.gif",
        ":s2:": "632fd22561.gif",
        ":s3:": "818813b1b6.gif",
        ":s4:": "8720a40116.gif",
        "+_+": "8228259e61.gif",
        ":!:": "a3090648d2.gif",
        ":-(": "782a30df3b.gif",
        ":-D": "a8f0d06e0d.gif",
        ":-P": "8004064b17.gif",
        ":-o": "dfed8d538f.gif",
        ":V:": "0c60c850a0.gif",
        ":s:": "c42ba136f3.gif",
        ":(": "4f8bc8dff7.gif",
        ":)": "50585be4e3.gif",
        ":D": "8f0d738822.gif",
    ]

    /// All tokens, sorted longest-first. Used by the parser so that longer
    /// tokens are matched before any shorter prefix-overlapping ones.
    static let tokensLongestFirst: [String] = entries.keys
        .sorted { ($0.count, $0) > ($1.count, $1) }

    /// Resolves a token to a bundle URL. Returns nil if the asset is missing
    /// (should not happen in production builds, but keep defensive).
    /// Xcode 16 synced groups flatten unknown file types into `Resources/`,
    /// so we try a `Smileys/` subdirectory first (in case the folder is
    /// preserved) and fall back to a flat lookup.
    static func url(for token: String) -> URL? {
        guard let filename = entries[token] else { return nil }
        let stem = (filename as NSString).deletingPathExtension
        let ext  = (filename as NSString).pathExtension
        return Bundle.main.url(forResource: stem, withExtension: ext, subdirectory: "Smileys")
            ?? Bundle.main.url(forResource: stem, withExtension: ext)
    }

    /// In-memory NSImage cache keyed by token. NSImage retains the GIF data
    /// internally, so a single load per token is enough for both the static
    /// first-frame render path and any future animated path.
    private static let imageCache = NSCache<NSString, NSImage>()

    static func image(for token: String) -> NSImage? {
        let key = token as NSString
        if let hit = imageCache.object(forKey: key) { return hit }
        guard let url = url(for: token), let img = NSImage(contentsOf: url) else { return nil }
        imageCache.setObject(img, forKey: key)
        return img
    }
}
