#!/usr/bin/env python3
# Downloads Shikimori smiley GIFs and regenerates SmileyCatalog.swift.
#
# Usage:
#   python3 scripts/fetch_smileys.py                # uses bundled token list
#   python3 scripts/fetch_smileys.py path/to.html   # extract tokens from a saved HTML page
#
# Files are written into MyShikiPlayer/Resources/Smileys/ as md5(token)[:10].gif.
# The Swift catalog is generated at MyShikiPlayer/Social/SmileyCatalog.swift.
# Run the script whenever Shikimori adds new smileys (paste the smiley-picker
# HTML into the optional argument, or extend BUNDLED_TOKENS below).
import hashlib
import json
import os
import re
import sys
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
ASSETS_DIR = os.path.join(REPO, "MyShikiPlayer", "Resources", "Smileys")
SWIFT_OUT = os.path.join(REPO, "MyShikiPlayer", "Social", "SmileyCatalog.swift")
URL_BASE = "https://shikimori.io/images/smileys/"

# Source of truth for the smiley list. To regenerate, paste the smiley-picker
# HTML from shikimori.io as the script argument; the script will replace this
# list automatically.
BUNDLED_TOKENS_PATH = os.path.join(os.path.dirname(__file__), "smileys_tokens.json")


def load_tokens(html_path: str | None) -> list[str]:
    if html_path:
        html = open(html_path, encoding="utf-8").read()
        tokens = []
        seen = set()
        for token, _ in re.findall(r'<img alt="([^"]+)"[^>]*src="([^"]+)"', html):
            if token in seen:
                continue
            seen.add(token)
            tokens.append(token)
        # Persist for future runs without HTML.
        with open(BUNDLED_TOKENS_PATH, "w", encoding="utf-8") as f:
            json.dump(tokens, f, ensure_ascii=False, indent=2)
        return tokens
    if not os.path.exists(BUNDLED_TOKENS_PATH):
        sys.exit(f"No tokens cached at {BUNDLED_TOKENS_PATH}. Pass HTML path as argv[1].")
    return json.load(open(BUNDLED_TOKENS_PATH, encoding="utf-8"))


def filename_for(token: str) -> str:
    return hashlib.md5(token.encode("utf-8")).hexdigest()[:10] + ".gif"


def fetch(token: str) -> tuple[str, bool, object]:
    out = os.path.join(ASSETS_DIR, filename_for(token))
    if os.path.exists(out) and os.path.getsize(out) > 0:
        return token, True, "cached"
    url = URL_BASE + token + ".gif"
    parsed = urllib.parse.urlsplit(url)
    safe_url = urllib.parse.urlunsplit((
        parsed.scheme,
        parsed.netloc,
        urllib.parse.quote(parsed.path, safe="/"),
        parsed.query,
        parsed.fragment,
    ))
    try:
        req = urllib.request.Request(safe_url, headers={"User-Agent": "MyShikiPlayer/1.0"})
        with urllib.request.urlopen(req, timeout=8) as r:
            data = r.read()
        with open(out, "wb") as f:
            f.write(data)
        return token, True, len(data)
    except Exception as e:
        return token, False, str(e)


def write_catalog(tokens: list[str]) -> None:
    sorted_tokens = sorted(tokens, key=lambda t: (-len(t), t))
    lines = [f'        "{t.replace(chr(92), chr(92) * 2).replace(chr(34), chr(92) + chr(34))}": "{filename_for(t)}",' for t in sorted_tokens]
    body = "\n".join(lines)
    swift = f"""//
//  SmileyCatalog.swift
//  MyShikiPlayer
//
//  Auto-generated by scripts/fetch_smileys.py — do not edit by hand.
//  Maps Shikimori smiley tokens (e.g. ":ololo:", ":-D", "+_+") to bundled
//  GIF filenames. Files live in Resources/Smileys/ as a folder reference.
//

import AppKit
import Foundation

enum SmileyCatalog {{
    /// Token → filename (under "Smileys" subdirectory in the app bundle).
    static let entries: [String: String] = [
{body}
    ]

    /// All tokens, sorted longest-first. Used by the parser so that longer
    /// tokens are matched before any shorter prefix-overlapping ones.
    static let tokensLongestFirst: [String] = entries.keys
        .sorted {{ ($0.count, $0) > ($1.count, $1) }}

    /// Resolves a token to a bundle URL. Returns nil if the asset is missing
    /// (should not happen in production builds, but keep defensive).
    /// Xcode 16 synced groups flatten unknown file types into `Resources/`,
    /// so we try a `Smileys/` subdirectory first (in case the folder is
    /// preserved) and fall back to a flat lookup.
    static func url(for token: String) -> URL? {{
        guard let filename = entries[token] else {{ return nil }}
        let stem = (filename as NSString).deletingPathExtension
        let ext  = (filename as NSString).pathExtension
        return Bundle.main.url(forResource: stem, withExtension: ext, subdirectory: "Smileys")
            ?? Bundle.main.url(forResource: stem, withExtension: ext)
    }}

    /// In-memory NSImage cache keyed by token. NSImage retains the GIF data
    /// internally, so a single load per token is enough for both the static
    /// first-frame render path and any future animated path.
    private static let imageCache = NSCache<NSString, NSImage>()

    static func image(for token: String) -> NSImage? {{
        let key = token as NSString
        if let hit = imageCache.object(forKey: key) {{ return hit }}
        guard let url = url(for: token), let img = NSImage(contentsOf: url) else {{ return nil }}
        imageCache.setObject(img, forKey: key)
        return img
    }}
}}
"""
    with open(SWIFT_OUT, "w", encoding="utf-8") as f:
        f.write(swift)


def main() -> int:
    os.makedirs(ASSETS_DIR, exist_ok=True)
    html_arg = sys.argv[1] if len(sys.argv) > 1 else None
    tokens = load_tokens(html_arg)
    print(f"Tokens: {len(tokens)}")

    ok, fail = 0, []
    with ThreadPoolExecutor(max_workers=20) as pool:
        for tok, success, info in (f.result() for f in as_completed(pool.submit(fetch, t) for t in tokens)):
            if success:
                ok += 1
            else:
                fail.append((tok, info))

    print(f"Downloaded: {ok}/{len(tokens)}")
    for tok, info in fail:
        print(f"  FAIL {tok!r}  {info}")

    write_catalog(tokens)
    print(f"Wrote {SWIFT_OUT}")
    files = sorted(os.listdir(ASSETS_DIR))
    total_kb = sum(os.path.getsize(os.path.join(ASSETS_DIR, f)) for f in files) / 1024
    print(f"Assets: {len(files)} files, {total_kb:.1f} KB")
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
